[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyrobloxbot"
version = "1.0.9"
authors = [
  { name="Mews", email="tiraraspas@gmail.com" },
]
description = "A python library to control the roblox character and interact with game ui through keyboard inputs"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
  "pydirectinput",
  "pygetwindow",
  "pyperclip",
  "pywin32",
  "keyboard",
  "pynput",
  "pyautogui",
  "opencv-python",
  "pillow",
]
keywords = ["roblox", "bot", "keyboard"]

[project.urls]
Homepage = "https://github.com/Mews/py-roblox-bot"
Issues = "https://github.com/Mews/py-roblox-bot/issues"
